# Generated by Django 5.1.1 on 2025-04-05 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_lostfounditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='time_reported',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
