# Generated by Django 5.1.1 on 2025-04-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_lostfounditem_time_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostfounditem',
            name='time_reported',
        ),
    ]
