# Generated by Django 5.1.1 on 2025-10-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0005_itemclaim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemClaim',
        ),
    ]
